// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abxxhnzbrkpgqzxewinu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieHhobnpicmtwZ3F6eGV3aW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTQ5NTAsImV4cCI6MjA2OTI3MDk1MH0.I-YTRakY1hiLJ382dhhXdgeMhzxPS7E8E4ZfihIgGTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});