// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgkopvnjernjhamvbnxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpna29wdm5qZXJuamhhbXZibnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNzkyNTMsImV4cCI6MjA4NDY1NTI1M30.Au08Tp1uMOAEyaXUGfRkKKEiQmMA8thx4klrT4xLCgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});